<?php

namespace Hardsystem\Correios\LogisticaReversa\Enum;

final class CodigoErroLR
{
    private const DESCRICOES = [
        3 => 'Não é permitido agendar processamento de arquivo via webservice',
        10 => 'O arquivo já foi processado',
        103 => 'Arquivo com erro de estrutura',
        104 => 'Dados de validação da coleta incompletos',
        105 => 'Cliente não configurado para usar o sistema',
        107 => 'Versão inválida do arquivo XML',
        108 => 'Valor declarado não pode ser superior a R$ 10.000,00',
        109 => 'Dados do contrato inválidos',
        111 => 'Coleta domiciliar não disponível para essa localidade',
        1111 => 'Coleta domiciliar não disponível para o serviço SEDEX 10',
        112 => 'Serviço não atende o CEP de destino',
        113 => 'CEP do destinatário inexistente',
        114 => 'CEP de destino com formato inválido',
        115 => 'CEP de origem com formato inválido',
        117 => 'CEP do remetente inexistente',
        120 => 'Serviço indisponível para o trecho informado',
        1201 => 'Serviço informado não abrange o CEP de origem',
        121 => 'E-ticket que já foi solicitado',
        122 => 'Dados de destinatário incompleto',
        125 => 'Dados de remetente incompletos',
        134 => 'Data de agendamento inválida. Verificar tag - AGENDAMENTO',
        136 => 'Número de entrega inválido',
        1366 => 'Serviço de simultânea em agência não atendido na região do CEP do remetente',
        138 => 'O arquivo não contém pedidos de coleta. Verificar tag - coletas solicitadas',
        140 => 'Cartão inválido para o contrato informado',
        142 => 'Valor inválido para o tipo de solicitação. Verificar tag - AG',
        195 => 'Número de e-ticket já utilizado',
        1955 => 'Número de objeto já utilizado nesse arquivo',
        198 => 'Número de objeto inválido ou dígito verificador incorreto',
        1988 => 'Faixa numérica não reservada para esse cliente',
        19888 => 'Número de objeto já utilizado',
        198888 => 'Tipo de etiqueta inválido',
        199 => "O serviço adicional 'Aviso de Recebimento' somente está disponível para os pedidos de Autorização de Postagem",
        200 => 'Código de checklist inválido',
        201 => 'Código do produto inválido',
        202 => 'Serviço especial SEDEX 10 não é atendido por Logística Reversa Domiciliária',
        203 => 'Valor tag - AR - inválido',
        204 => 'Tags - ENTREGA - inconsistentes',
        205 => 'Valor declarado inválido',
        206 => 'Tag - ENVIO.OBJ - inválida',
        207 => 'Data de processamento inválida. Verificar tag - DATA_PROCESSAMENTO',
        208 => 'Arquivo vazio',
        209 => 'Arquivo com mais de 300 coletas',
        210 => 'Serviço indisponível no momento',
        211 => 'Valor declarado não pode ser inferior a R$ 24,50',
        212 => 'ID de postagem inválido',
        213 => 'Valor inválido para a tag - QTD_CAIXA',
        214 => 'Tag - número - deve ser utilizado somente no serviço de Autorização de Postagem',
        215 => 'Tag - identificação - CPF ou CNPJ inválido',
        216 => 'UF inválida',
        217 => 'Tag - número - inválida',
        218 => 'Tag - cartão - inválida',
        219 => 'Tag - PRODUTO.CODIGO - inválida',
        220 => 'Tag - PRODUTO.TIPO - inválida',
        221 => 'Tag - PRODUTO.QTD - inválida',
        222 => 'O CEP informado não pertence a faixa de abrangência do serviço e-SEDEX Grupo I',
        223 => 'O CEP informado não pertence a faixa de abrangência do serviço e-SEDEX Grupo II',
        224 => 'Tipo da solicitação inválida',
        225 => 'Serviço inválido',
        226 => 'Quantidade inválida',
        227 => 'O número deve possuir 8 dígitos',
        228 => 'Quantidade de objetos superior ao permitido',
        229 => 'Tag - SMS - inválida',
        230 => 'Tag - DDD_CELULAR - inválida',
        231 => 'Tag - CELULAR - inválida',
        232 => 'Os documentos para o preenchimento do checklist não foram informados no pedido',
        233 => 'Só é permitido o máximo de 8 documentos para a validação no checklist',
        234 => 'Tipo de checklist informado não encontrado',
        235 => 'O serviço informado não abrange o serviço de checklist documento',
        236 => 'A data da Autorização de Postagem é superior a data de vigência do contrato',
        237 => 'Código administrativo inválido',
        238 => 'Quantidade de caracteres superior ao permitido. Verificar a tag',
        239 => 'A tag documento não é permitida para o tipo de checklist informado',
        240 => 'Ao informar a relação de documentos é obrigatório indicar o checklist a ser utilizado',
        241 => 'O CEP do remetente foi alterado. Informar CEP atual',
        242 => 'O CEP do destinatário foi alterado. Informar CEP atual',
        243 => 'Em virtude das restrições de mobilidade urbana durante os Jogos Olímpicos, no período de 28/07/2016 a 18/09/2016, o serviço de Logística Reversa com coleta está suspenso temporariamente para esta localidade',
        244 => 'Em virtude das restrições de mobilidade urbana durante os Jogos Olímpicos, no período de 28/07/2016 a 18/09/2016, o serviço de SEDEX 10 está temporariamente suspenso para essa localidade',
        245 => 'O serviço está encerrado. O prazo de validade é superior a validade do serviço',
        246 => 'A solicitação já foi cadastrada',
        247 => 'Não foi possível solicitar novo range. É necessário consumir no mínimo 80% da última solicitação',
        248 => 'Validação do serviço no SCPP',
        249 => 'Tag - EMAIL - inválido',
        250 => 'CEP de Clique e Retire deverá informar DDD e celular do destinatário',
        251 => 'Tag - DDD_TELEFONE - inválida',
        252 => 'Tag - TELEFONE - inválida',
        253 => 'O adicional valor declarado não está disponível para o serviço informado',
        254 => 'A aquisição de embalagem não está disponível para o serviço informado',
        255 => 'O serviço adicional checklist não está disponível para o serviço informado',
        256 => 'Tipo de coleta inválido para o serviço informado',
        -1 => 'Código do identificador de acesso ao web service não autorizado',
        -3 => 'Tipo de solicitação inválida',
        -4 => 'Tipo de busca inválido',
        -5 => 'Número do pedido inválido ou não localizado na base de dados para o tipo de solicitação informado',
        -7 => 'Dados obrigatórios não informados',
        -8 => 'Não existe informação para o solicitado',
        -9 => 'Pedido não pode ser cancelado, pois encontra-se no status',
        -10 => 'O limite de pedidos deve ser no máximo de 30',
        -11 => 'Serviço indisponível no momento',
        -12 => 'O número do pedido deve ser um valor numérico',
        -13 => 'Não existe informação para os critérios informados',
        -14 => 'Por favor, informe uma data válida (formato: DD/MM/YYYY)',
        -15 => 'Por favor, informe um valor entre 5 e 30 dias corridos para a revalidação do e-ticket',
        -16 => 'O e-ticket informado ainda está ativo',
        -17 => 'O e-ticket informado já foi utilizado. Sendo assim, não é possível a revalidação',
        -18 => 'O novo prazo para a Autorização de Postagem é superior a data de vigência do contrato',
    ];

    public static function descricaoDe(int $codigo): ?string
    {
        return self::DESCRICOES[$codigo] ?? null;
    }

    public static function conhecido(int $codigo): bool
    {
        return isset(self::DESCRICOES[$codigo]);
    }
}
